# Generated by Django 2.1.3 on 2018-11-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_accesorio_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Marca'),
            preserve_default=False,
        ),
    ]
